services:
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017
    environment:
      - MONGO_URL=${MONGO_URL}
  deliveryservice:
    build: .
    restart: always
    ports:
      - 3000:3001
    environment:
      - HTTP_PORT=${HTTP_PORT:3000}
    depends_on:
      - mongo
